# This rule is not used by the project agent itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apptrail.apptrail.sh.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/managed-by: kustomize
  name: workloadrolloutstate-editor-role
rules:
- apiGroups:
  - apptrail.apptrail.sh
  resources:
  - workloadrolloutstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apptrail.apptrail.sh
  resources:
  - workloadrolloutstates/status
  verbs:
  - get

