# This rule is not used by the project agent itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apptrail.apptrail.sh resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/managed-by: kustomize
  name: workloadrolloutstate-viewer-role
rules:
- apiGroups:
  - apptrail.apptrail.sh
  resources:
  - workloadrolloutstates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apptrail.apptrail.sh
  resources:
  - workloadrolloutstates/status
  verbs:
  - get

